FROM jupyter/tensorflow-notebook:python-3.9.7

USER root

RUN apt-get update && \
    apt-get install -y libsecret-1-0 libsecret-1-dev libglib2.0-dev

USER ${NB_UID}

RUN conda install --quiet --yes -c fastchan fastai

RUN mamba install --quiet --yes \
    'mlflow' \
    'python-dotenv' \
    'jupyterlab-git' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"