FROM jupyter/tensorflow-notebook:python-3.9.7

USER ${NB_UID}

RUN conda install --quiet --yes -c fastchan fastai

RUN mamba install --quiet --yes \
    'python-dotenv' \
    'jupyterlab-git' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"