FROM jupyter/tensorflow-notebook:python-3.9.7

USER root

RUN apt-get update && \
    apt-get install -y libsecret-1-0 libsecret-1-dev libglib2.0-dev

USER ${NB_UID}

RUN pip install interpret --quiet

RUN mamba install --quiet -y \
    'mlflow' \
    'python-dotenv' \
    'imbalanced-learn' \
    'sktime-all-extras' \
    'jupyterlab-git' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"