FROM jupyter/tensorflow-notebook:python-3.9.10

USER root

USER ${NB_UID}

RUN pip install interpret --quiet

RUN mamba install --quiet -y \
    'mlflow' \
    'python-dotenv' \
    'imbalanced-learn' \
    'sktime-all-extras' \
    'jupyterlab-git' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
